### ISSUE TITLE
error when push  

### ISSUE THREAD

**Issue by mickeyrouash** [Goodsmileduck/helm-push-action#11]
it starts today:
failed to load plugins: two plugins claim the name "push" at "/opt/xdg/helm/plugins/helm-push.git" and "/opt/xdg/helm/plugins/https-github.com-chartmuseum-helm-push.git"

**Comment by unixfox** [comment]
Probably because helm push is now included in the binary and installing helm push from https://github.com/chartmuseum/helm-push.git is not needed anymore.

**Comment by Goodsmileduck** [comment]
sorry, looks like it's related to issue https://github.com/chartmuseum/helm-push/issues/84
even locally it's working, inside the container it's not
I set version to 3.3.1 and it's working now, v3 and v2 releases also updated.
Please try again.

**Comment by Goodsmileduck** [comment]
btw

**Comment by unixfox** [comment]
Great let's keep the version of helm that works for the moment.

This bug is weird tho because helm push works great with the latest version on Ubuntu 20.04.
